/*
 * This source file was generated by the Gradle 'init' task
 */
package org.ldemetrios.kscript

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.CliktError
import com.github.ajalt.clikt.core.parse
import com.github.ajalt.clikt.parameters.arguments.argument
import com.github.ajalt.clikt.parameters.arguments.optional
import com.github.ajalt.clikt.parameters.groups.default
import com.github.ajalt.clikt.parameters.groups.mutuallyExclusiveOptions
import com.github.ajalt.clikt.parameters.options.convert
import com.github.ajalt.clikt.parameters.options.default
import com.github.ajalt.clikt.parameters.options.flag
import com.github.ajalt.clikt.parameters.options.option
import com.github.ajalt.clikt.parameters.types.file
import java.nio.file.Files
import java.nio.file.attribute.PosixFilePermission
import kotlin.io.path.createTempDirectory
import kotlin.io.path.writeBytes

class ApplicationContext : CliktCommand(
    name = "kscript", // Replace with your app's name
) {
    private val inputFile by argument(
        name = "SOURCE",
        help = "Input file."
    ).file(mustExist = true, canBeFile = true, canBeDir = false).optional()

    private val stdinFlag by option("-s", "--stdin", help = "Read from standard input.").flag()

    val configFile by option(
        "--config-file", "-c",
        help = "Path to the configuration file."
    ).file(mustExist = true, canBeFile = true, canBeDir = false)

    val commentPrefix by option(
        "--comment-prefix", "-p",
        help = "The prefix used for comments."
    ).default("!")

    val gradleHome by option(
        "--gradle-home", "-g",
        help = "The Gradle home directory."
    ).file(mustExist = true, canBeFile = false, canBeDir = true)

    val clean by option(
        "--clean",
        help = "Clear build cache. (reserved, not supported yet)"
    ).flag()

    val logLevel by mutuallyExclusiveOptions(
        option("--debug", help = "Debug mode.").flag().convert { LogLevel.DEBUG },
        option("--info", help = "Info mode.").flag().convert { LogLevel.INFO },
        option("--warn", help = "Warn mode (default).").flag().convert { LogLevel.WARN },
        option("--error", help = "Error mode.").flag().convert { LogLevel.ERROR },
        option("--fatal", help = "Fatal mode.").flag().convert { LogLevel.FATAL },
    ).default(LogLevel.WARN)

    lateinit var freeArgs: List<String>
        private set

    fun execute(args: List<String>): Int {
        val splitter = args.indexOf("--")
        freeArgs = if (splitter >= 0) args.subList(splitter + 1, args.size) else emptyList()
        val parsedArgs = if (splitter >= 0) args.subList(0, splitter) else args
        try {
            parse(parsedArgs)
            return 0
        } catch (e: CliktError) {
            echoFormattedHelp(e)
            return e.statusCode
        } catch (e: PropagateCode) {
            return e.code
        }
    }

    override fun run() {
        if (inputFile != null && stdinFlag) {
            throw CliktError("Cannot use both input file and standard input.")
        }

        debug { "[ApplicationContext] Reading input" }
        val code = inputFile?.readLines() ?: System.`in`.bufferedReader().readLines()

        val regex = Regex("\\s*//$commentPrefix(.*)")
        val configPart = code.mapNotNull {
            regex.matchEntire(it)?.groupValues?.last()
        }

        debug { "[ApplicationContext] Found ${configPart.size} config lines" }

        val processedConfig = mutableListOf<ConfigEntry>()
        val functions = mutableMapOf<String, FunctionDeclEntry>()
        if (configFile != null) {
            info { "[ApplicationContext] Using config file $configFile" }
            processedConfig.preprocess(configFile!!.toPath(), configFile!!.readLines(), functions)
        } else {
            info { "No config file specified" }
        }
        debug { "[ApplicationContext] Found ${functions.size} functions: ${functions.keys.joinToString(", ")}" }
        info { "[ApplicationContext] Processing source file's config" }
        processedConfig.preprocess(inputFile?.toPath(), configPart, functions)

        info { "[ApplicationContext] Resolving config" }
        val project = resolve(processedConfig, code.joinToString("\n")).toMutableMap()
        project["src/main/kotlin/kscript/EntryPoint.kt"] =
            ("package kscript;\n" + code.filter { !it.trim().startsWith("#!") }.joinToString("\n")).toByteArray()
        project["gradle/wrapper/gradle-wrapper.jar"] =
            ApplicationContext::class.java.getResourceAsStream("/gradle-init/gradle/wrapper/gradle-wrapper.jar")!!.readBytes()

        val projectDir = createTempDirectory("kscript-")
        info { "[ApplicationContext] Creating project in $projectDir" }
        for ((file, content) in project) {
            debug { "[ApplicationContext] Writing file $file" }
            projectDir.resolve(file).run {
                parent.toFile().mkdirs()
                writeBytes(content)
            }
        }
        info { "[ApplicationContext] Project created, launching gradle" }

        val executable = gradleHome?.path ?: if (System.getProperty("os.name").startsWith("Windows")) {
            "gradlew.bat"
        } else {
            "./gradlew"
        }

        // Check if we're on a POSIX-compliant system
        val gradlew = projectDir.resolve("gradlew")
        if (Files.getFileStore(gradlew).supportsFileAttributeView("posix")) {
            val permissions = Files.getPosixFilePermissions(gradlew)
            val newPermissions = mutableSetOf<PosixFilePermission>().apply {
                addAll(permissions)
                add(PosixFilePermission.OWNER_EXECUTE)
                add(PosixFilePermission.GROUP_EXECUTE)
                add(PosixFilePermission.OTHERS_EXECUTE)
            }
            Files.setPosixFilePermissions(gradlew, newPermissions)
        }

        val command = buildList {
            add(executable)
            add("run")
            if (freeArgs.isNotEmpty()) {
                add("--args=" + freeArgs.joinToString(" ") { "'" + it.replace("'", "'\\''") + "'" })
            }
        }
        debug { "[ApplicationContext] Running command $command" }
        val builder = ProcessBuilder(command)
            .directory(projectDir.toFile())
            .redirectOutput(ProcessBuilder.Redirect.INHERIT)
            .redirectError(ProcessBuilder.Redirect.INHERIT)
            .redirectInput(ProcessBuilder.Redirect.INHERIT)

        val env: MutableMap<String, String?> = builder.environment()
        env["JAVA_HOME"] = detectJavaHome()

        val process = builder.start()
        val exitCode = process.waitFor()
        info { "[ApplicationContext] Gradle exited with code $exitCode" }
        throw PropagateCode(exitCode)
    }
}

fun main(args: Array<String>) {
    ApplicationContext().execute(args.asList())
}

private class PropagateCode(val code: Int) : RuntimeException()